spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: anna
    password: trytoguess
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
        hibernate.format_sql: true
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  liquibase:
    change-log: classpath:db/changelog-master.xml